# -*- coding: utf-8 -*-
"""app.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/12R3BEyaaTm0ZGb-LESQJV0Mhose7yKQ3
"""

import streamlit as st
import cv2
import numpy as np
import tempfile
from utils.dms_core import process_frame

st.set_page_config("Driver Monitoring System", layout="wide")
st.title("🚗 Driver Monitoring System (Web Interface)")

mode = st.sidebar.radio(
    "Select Mode",
    ["Upload Video", "Webcam (Capture)"]
)

frame_box = st.empty()

# ================= VIDEO UPLOAD MODE =================
if mode == "Upload Video":
    uploaded = st.file_uploader("Upload driving video", type=["mp4", "avi", "mov"])

    if uploaded:
        tfile = tempfile.NamedTemporaryFile(delete=False)
        tfile.write(uploaded.read())

        cap = cv2.VideoCapture(tfile.name)
        fps = cap.get(cv2.CAP_PROP_FPS) or 25
        closed_frames = 0

        st.info("Processing video...")

        while cap.isOpened():
            ret, frame = cap.read()
            if not ret:
                break

            frame, closed_frames, _ = process_frame(
                frame, closed_frames, fps
            )

            frame = cv2.cvtColor(frame, cv2.COLOR_BGR2RGB)
            frame_box.image(frame)

        cap.release()
        st.success("Video processing completed ✅")

# ================= WEBCAM MODE =================
else:
    st.warning("Webcam works as frame capture on cloud (browser limitation)")
    img = st.camera_input("Capture image")

    if img:
        file_bytes = np.asarray(bytearray(img.read()), dtype=np.uint8)
        frame = cv2.imdecode(file_bytes, 1)

        frame, _, _ = process_frame(frame, 0, fps=25)

        frame = cv2.cvtColor(frame, cv2.COLOR_BGR2RGB)
        frame_box.image(frame)